<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="178780" started-at="2016-12-12T12:48:49Z" finished-at="2016-12-12T12:51:48Z">
    <groups>
      <group name="JDaddress">
        <method signature="JDaddress.testJD()[pri:0, instance:main.java.com.dbyl.tests.JDaddress@21129f1f]" name="testJD" class="main.java.com.dbyl.tests.JDaddress"/>
      </group> <!-- JDaddress -->
      <group name="useCookies">
        <method signature="UseCookieLogin.useCookies()[pri:0, instance:main.java.com.dbyl.tests.UseCookieLogin@5a9f4771]" name="useCookies" class="main.java.com.dbyl.tests.UseCookieLogin"/>
      </group> <!-- useCookies -->
      <group name="MapTest">
        <method signature="MapTest.mapTest()[pri:0, instance:main.java.com.dbyl.tests.MapTest@282cb7c7]" name="mapTest" class="main.java.com.dbyl.tests.MapTest"/>
      </group> <!-- MapTest -->
      <group name="loginTest">
        <method signature="loginTest.loginByUerName()[pri:0, instance:main.java.com.dbyl.tests.loginTest@7d898981]" name="loginByUerName" class="main.java.com.dbyl.tests.loginTest"/>
      </group> <!-- loginTest -->
    </groups>
    <test name="TestDebug" duration-ms="178780" started-at="2016-12-12T12:48:49Z" finished-at="2016-12-12T12:51:48Z">
      <class name="main.java.com.dbyl.tests.loginTest">
        <test-method status="PASS" signature="init()[pri:0, instance:main.java.com.dbyl.tests.loginTest@7d898981]" name="init" is-config="true" duration-ms="15965" started-at="2016-12-12T20:48:49Z" finished-at="2016-12-12T20:49:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
      </class> <!-- main.java.com.dbyl.tests.loginTest -->
      <class name="main.java.com.dbyl.tests.UseCookieLogin">
        <test-method status="PASS" signature="beforeRun()[pri:0, instance:main.java.com.dbyl.tests.UseCookieLogin@5a9f4771]" name="beforeRun" is-config="true" duration-ms="3289" started-at="2016-12-12T20:48:49Z" finished-at="2016-12-12T20:48:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeRun -->
        <test-method status="PASS" signature="afterTearDown()[pri:0, instance:main.java.com.dbyl.tests.UseCookieLogin@5a9f4771]" name="afterTearDown" is-config="true" duration-ms="142" started-at="2016-12-12T20:49:08Z" finished-at="2016-12-12T20:49:08Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTearDown -->
      </class> <!-- main.java.com.dbyl.tests.UseCookieLogin -->
      <class name="main.java.com.dbyl.tests.MapTest">
        <test-method status="FAIL" signature="beforeTest()[pri:0, instance:main.java.com.dbyl.tests.MapTest@282cb7c7]" name="beforeTest" is-config="true" duration-ms="0" started-at="2016-12-12T20:48:49Z" finished-at="2016-12-12T20:48:49Z">
          <exception class="org.openqa.selenium.remote.UnreachableBrowserException">
            <message>
              <![CDATA[Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: 'unknown', revision: '350cf60', time: '2016-10-13 10:46:00 -0700'
System info: host: 'Youngs-MacBook-Pro.local', ip: '192.168.1.102', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_92'
Driver info: driver.version: RemoteWebDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: 'unknown', revision: '350cf60', time: '2016-10-13 10:46:00 -0700'
System info: host: 'Youngs-MacBook-Pro.local', ip: '192.168.1.102', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.12.1', java.version: '1.8.0_92'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:622)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:241)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:128)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:155)
	at main.java.com.dbyl.libarary.utils.DriverFactory.getRemoteDriver(DriverFactory.java:182)
	at main.java.com.dbyl.tests.MapTest.beforeTest(MapTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeBeforeClassMethods(TestMethodWorker.java:169)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:812)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to localhost:4444 [localhost/127.0.0.1, localhost/0:0:0:0:0:0:0:1] failed: errno: 61 (Connection refused), error: Connection refused (local port 51855 to address 0:0:0:0:0:0:0:1 (localhost), remote port 4444 to address 0:0:0:0:0:0:0:1 (localhost))
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:142)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:88)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:108)
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:64)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
	... 18 more
Caused by: java.net.ConnectException: errno: 61 (Connection refused), error: Connection refused (local port 51855 to address 0:0:0:0:0:0:0:1 (localhost), remote port 4444 to address 0:0:0:0:0:0:0:1 (localhost))
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:591)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 33 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.remote.UnreachableBrowserException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="SKIP" signature="mapTest()[pri:0, instance:main.java.com.dbyl.tests.MapTest@282cb7c7]" name="mapTest" duration-ms="2" started-at="2016-12-12T20:48:51Z" finished-at="2016-12-12T20:48:51Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mapTest -->
        <test-method status="FAIL" signature="afterTest()[pri:0, instance:main.java.com.dbyl.tests.MapTest@282cb7c7]" name="afterTest" is-config="true" duration-ms="0" started-at="2016-12-12T20:48:51Z" finished-at="2016-12-12T20:48:51Z">
          <exception class="java.lang.NullPointerException">
            <message>
              <![CDATA[while trying to invoke the method org.openqa.selenium.WebDriver.quit() of a null object loaded from field main.java.com.dbyl.tests.MapTest.driver of an object loaded from local variable 'this']]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException: while trying to invoke the method org.openqa.selenium.WebDriver.quit() of a null object loaded from field main.java.com.dbyl.tests.MapTest.driver of an object loaded from local variable 'this'
	at main.java.com.dbyl.tests.MapTest.afterTest(MapTest.java:111)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:812)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- main.java.com.dbyl.tests.MapTest -->
      <class name="main.java.com.dbyl.tests.JDaddress">
        <test-method status="PASS" signature="tearDown()[pri:0, instance:main.java.com.dbyl.tests.JDaddress@21129f1f]" name="tearDown" is-config="true" duration-ms="101" started-at="2016-12-12T20:51:48Z" finished-at="2016-12-12T20:51:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- main.java.com.dbyl.tests.JDaddress -->
    </test> <!-- TestDebug -->
  </suite> <!-- Suite -->
</testng-results>
